trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: yvt/rust-azure-pipelines
      ref: refs/heads/master
      endpoint: PipelinesTemplates

variables:
  rustVersion: nightly-2019-10-13
  linuxPrestep: |
    sudo apt-get update &&
    sudo apt-get install -y \
      libglib2.0-dev libcairo2-dev libcairo-gobject2 libpango1.0-dev
  linuxVmImage: ubuntu-18.04

stages:
- stage: check
  displayName: "Quick checks"
  jobs:
  - template: ci/jobs/cargo-check.yml@rust_pipelines
    parameters:
      rust: $(rustVersion)
      all: true
      benches: true
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
      job_pre-steps:
        - script: ${{ variables.linuxPrestep }}
          displayName: Install native dependencies
  - template: ci/jobs/rustfmt.yml@rust_pipelines
    parameters:
      rust: $(rustVersion)
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
  - template: ci/jobs/cargo-clippy.yml@rust_pipelines
    parameters:
      rust: $(rustVersion)
      all: true
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
      job_pre-steps:
        - script: ${{ variables.linuxPrestep }}
          displayName: Install native dependencies

- stage: test
  displayName: "Multi OS native tests"
  jobs:
  - template: ci/jobs/cargo-test.yaml@rust_pipelines
    parameters:
      rust: $(rustVersion)
      test-flags:
        nocapture: true
      all: true
      job_strategy:
        matrix:
          Linux:
            vmImage: ${{ variables.linuxVmImage }}
            prepareScript: ${{ variables.linuxPrestep }}
          MacOS:
            vmImage: macOS-10.13
            prepareScript: ""    # TODO
          Windows:
            vmImage: vs2017-win2016
            prepareScript: ""    # TODO

