[workspace]
members = [
    "stella2",
    "tcw3",
    "support/cggeom",
    "support/iterpool",
]

[profile.release]
debug = true
panic = "abort"

[profile.bench]
lto = true
debug = true
incremental = false
