[workspace]
members = [
    "stella2",
    "tcw3",
    "support/cggeom",
    "support/iterpool",
]

[profile.release]
debug = true
panic = "abort"
lto = true

[profile.bench]
lto = true
debug = true
incremental = false

# The following two include:
# “Expose more APIs on CGContext”
# <https://github.com/servo/core-foundation-rs/pull/313>
[patch.crates-io.core-graphics]
git = "https://github.com/yvt/core-foundation-rs.git"
rev = "2d5bdcc9b529bdaddaf45b36588e318aecd28fa3"
[patch.crates-io.core-foundation]
git = "https://github.com/yvt/core-foundation-rs.git"
rev = "2d5bdcc9b529bdaddaf45b36588e318aecd28fa3"
