[target.x86_64-apple-darwin.dependencies.std]
# Build without the backtrace functionality. It's not used at all because we
# rely on macOS's CrashReporter.
features = []
default-features = false

[target.x86_64-pc-windows-msvc.dependencies.std]
# Build without the backtrace functionality.
features = []
default-features = false
