[package]
name = "stella2_assets"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
stvg_macro = { path = "../stvg/macro" }

[build-dependencies]
embed-resource = "1.3.0"
icon_baker = "2.2.0"
libflate = "0.1.27"
