# Builds a release package for each target platform.
jobs:

# macOS
# -------------------------------------------------------------------------
- job: publish_macOS
  displayName: Publish for macOS
  continueOnError: true
  pool:
    vmImage: macOS-10.13
  variables:
  - template: ../common.yml
  steps:
  - template: ../steps/install-rust.yml
    parameters:
      rustup_toolchain: ${{ variables.rustVersion }}
      components: [ rust-src ]
  - script: cargo install xargo --version 0.3.17
    displayName: Install xargo
  - script: ./build-mac.sh
    displayName: build-mac.sh
  - task: ArchiveFiles@2
    displayName: Archive the application package
    inputs:
      rootFolderOrFile: ./publish
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/Stella2-$(Build.SourceVersion)-macOS.zip
  - task: PublishBuildArtifacts@1
    displayName: "Publish"
    inputs:
      artifactName: Stella2-nightly-macOS

# TODO: Windows
