[package]
name = "stvg_macro"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[dependencies]
proc-macro-hack = "0.5.11"
stvg_macro_impl = { path = "./impl" }
stvg_io = { path = "../io" }
