[package]
name = "atom2"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"

[target.'cfg(target_os = "windows")'.dependencies]
winrt = { version = "0.6.0", default-features = false, optional = true }
