trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

variables:
  rustVersion: nightly-2019-10-13
  linuxPrestep: |
    sudo apt-get update &&
    sudo apt-get install -y \
      libglib2.0-dev libcairo2-dev libcairo-gobject2 libpango1.0-dev
  linuxVmImage: ubuntu-18.04

stages:
- stage: check
  displayName: "Quick checks"
  jobs:
  - template: ./jobs/cargo-check.yml
    parameters:
      rust: $(rustVersion)
      all: true
      benches: true
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
      job_pre-steps:
        - script: ${{ variables.linuxPrestep }}
          displayName: Install native dependencies
  - template: ./jobs/rustfmt.yml
    parameters:
      rust: $(rustVersion)
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
  - template: ./jobs/cargo-clippy.yml
    parameters:
      rust: $(rustVersion)
      all: true
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
      job_pre-steps:
        - script: ${{ variables.linuxPrestep }}
          displayName: Install native dependencies

- stage: test
  displayName: "Multi OS native tests"
  jobs:
  - template: ./jobs/cargo-test.yml
    parameters:
      rust: $(rustVersion)
      all: true
      job_strategy:
        matrix:
          Linux:
            vmImage: ${{ variables.linuxVmImage }}
            prepareScript: |
              ${{ variables.linuxPrestep }}

              # Enable tests that depend on the testing backend. This needs
              # additional native dependencies (included in `linuxPrestep`) and
              # adds too much a hassle for other platforms, especially
              # Windows + MSVC.
              echo '##vso[task.setvariable variable=test_build_flags]$(test_build_flags) --features testing'
          MacOS:
            vmImage: macOS-10.13
            prepareScript: ""
          # TODO: Windows does not have its own backend at the moment
          # Windows:
          #   vmImage: vs2017-win2016
          #   prepareScript: ""

