trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

variables:
- template: ./common.yml

stages:
- stage: check
  displayName: "Quick checks"
  jobs:
  - template: ./jobs/cargo-check.yml
    parameters:
      rust: ${{ variables.rustVersion }}
      all: true
      benches: true
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
      job_pre-steps:
        - script: ${{ variables.linuxPrestep }}
          displayName: Install native dependencies
  - template: ./jobs/cargo-check.yml
    parameters:
      rust: ${{ variables.rustVersion }}
      all: true
      benches: true
      job_name: cargo_check_noassert
      job_displayName: Cargo check (no debug assertions)
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
      job_pre-steps:
        - script: ${{ variables.linuxPrestep }}
          displayName: Install native dependencies
        - script: |
            echo "[profile.test]" >> Cargo.toml
            echo "debug-assertions = false" >> Cargo.toml
          displayName: Disable debug assertions
  - template: ./jobs/rustfmt.yml
    parameters:
      rust: ${{ variables.rustVersion }}
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
  - template: ./jobs/cargo-clippy.yml
    parameters:
      rust: ${{ variables.rustVersion }}
      all: true
      job_pool:
        vmImage: ${{ variables.linuxVmImage }}
      job_pre-steps:
        - script: ${{ variables.linuxPrestep }}
          displayName: Install native dependencies

- stage: test
  displayName: "Multi OS native tests"
  jobs:
  - template: ./jobs/cargo-test.yml
    parameters:
      rust: ${{ variables.rustVersion }}
      all: true
      job_strategy:
        matrix:
          Linux:
            vmImage: ${{ variables.linuxVmImage }}
            prepareScript: |
              ${{ variables.linuxPrestep }}

              # Enable tests that depend on the testing backend. This needs
              # additional native dependencies (included in `linuxPrestep`) and
              # adds too much a hassle for other platforms, especially
              # Windows + MSVC.
              #
              # However, you can't use `--feature` when testing a whole
              # workspace (rust-lang/cargo#6195). So we use `--all-features`
              # instead.
              echo '##vso[task.setvariable variable=test_build_flags]$(test_build_flags) --all-features'

              # Disable tests that depend on the native backend because the test
              # environment has no access to X11 or Wayland.
              echo '##vso[task.setvariable variable=ST_SKIP_NATIVE_BACKEND_TESTS]1'
          MacOS:
            vmImage: macOS-10.14
            prepareScript: ""
          Windows:
            vmImage: windows-2019
            prepareScript: ""

