[package]
name = "tcw3_pal"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT"

[features]
default = ["macos_winit"]

# This flag enables the use of `winit` in the macOS backend for creating
# windows and handling input events. Whether this should be default or not is
# yet to be determined. After it's decided, this feature flag probably should be
# remove.
macos_winit = ["winit"]

[dependencies]
alt_fp = { path = "../../support/alt_fp" }
array = "0.0.1"
arrayvec = "0.5"
bitflags = "1.1.0"
cfg-if = "0.1.7"
cggeom = { path = "../../support/cggeom", features = ["quickcheck"] }
cgmath = "0.17.0"
checked = "0.5.0"
flags-macro = "0.1.3"
fragile = "0.3.0"
iterpool = { path = "../../support/iterpool" }
itertools = "0.8.0"
once_cell = "1.2.0"
owning_ref = "0.4.0"
packed_simd = "0.3.0"
rgb = "0.8.13"
svgbobdoc = "0.2"
winit = { version = "0.20.0-alpha3", optional = true }
zerocopy = "0.2.8"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.19.0"
core-foundation = "0.6"
core-graphics = "0.17.3"
core-text = "13.2.0"
dispatch = "0.1.4"
lazy_static = "1"
objc = "0.2.3"

# `unix` backend
[target.'cfg(not(target_os = "macos"))'.dependencies]
winit = "0.20.0-alpha3"
swsurface = "0.1.2"
cairo-rs = "0.7.1"
pangocairo = "0.8.0"
pango = "0.7.0"
rayon = "1.2.0"

[build-dependencies]
cc = "1.0.35"

[dev-dependencies]
env_logger = "0.7.0"
quickcheck = "0.9"
quickcheck_macros = "0.8"
log = "0.4"
structopt = "0.3.0"
arg_enum_proc_macro = "0.3.0"
