[package]
name = "tcw3_pal"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT"

[features]
default = ["macos_winit"]

# This flag enables the use of `winit` in the macOS backend for creating
# windows and handling input events. Whether this should be default or not is
# yet to be determined. After it's decided, this feature flag probably should be
# remove.
macos_winit = ["winit"]

[dependencies]
alt_fp = { path = "../../support/alt_fp" }
array = "0.0.1"
arrayvec = "0.4.10"
bitflags = "1.1.0"
cfg-if = "0.1.7"
cggeom = { path = "../../support/cggeom" }
cgmath = "0.17.0"
flags-macro = "0.1.3"
fragile = "0.3.0"
iterpool = { path = "../../support/iterpool" }
itertools = "0.8.0"
once_cell = { version = "0.2.4", default-features = false }
packed_simd = "0.3.0"
rgb = "0.8.13"
svgbobdoc = "0.2"
winit = { version = "0.20.0-alpha2", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.18.4"
core-foundation = "0.6"
core-graphics = "0.17.3"
core-text = "13.2.0"
dispatch = "0.1.4"
lazy_static = "1"
objc = "0.2.3"

[build-dependencies]
cc = "1.0.35"

[dev-dependencies]
pretty_env_logger = "0.3.0"
