[package]
name = "tcw3"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT"

[dependencies]
cfg-if = "0.1.7"
cgmath = "0.17.0"
rgb = "0.8.13"
bitflags = "1.0.4"
cggeom = { path = "../support/cggeom" }
flags-macro = "0.1.3"
derive_more = "0.14.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.3"
cocoa = "0.18.4"
core-foundation = "0.6"
core-graphics = "0.17.3"
iterpool = { path = "../support/iterpool" }

[build-dependencies]
cc = "1.0.35"
