[package]
name = "tcw3"
version = "0.1.0"
authors = ["yvt <i@yvt.jp>"]
edition = "2018"
license = "MIT"

[dependencies]
arrayvec = "0.4.10"
cgmath = "0.17.0"
bitflags = "1.1.0"
cggeom = { path = "../support/cggeom" }
flags-macro = "0.1.3"
derive_more = "0.14.0"
subscriber_list = { path = "../support/subscriber_list" }
as_any = { path = "../support/as_any" }
alt_fp = { path = "../support/alt_fp" }
rope = { path = "../support/rope" }
svgbobdoc = "0.2"
sorted_diff = { path = "../support/sorted_diff" }
lazy_static = "1"
itertools = "0.8.0"
ndarray = "0.12.1"

tcw3_images = { path = "images" }
tcw3_pal = { path = "pal" }

[dependencies.momo]
git = "https://github.com/llogiq/momo.git"
rev = "3d9d9709a5675bf3f5ebddcb3c1ec8ccf91e9b40"

[dev-dependencies]
lipsum = "0.6.0"
structopt = "0.3.0"
env_logger = "0.6.2"
